belindas-closet-nestjs_sprint8_remove-unrelated-fields
SeattleColleges/belindas-closet-nestjs pull request #134
Opened 2024-06-07 05:32 UTC by alasali1

attempt to remove unrelated field

For this I tried to validate all of the fields so that you can only include the fields that apply to the productType.
I am still able to post an object with unrelated fields on postman though. So this is not fixed though this is my attempt.
Would appreciate some feedback.

2024-06-12 06:56 UTC, taylorpapke approved these changes
I think this is correct because when I take away the productSizeShoe field, it saves as an empty array:
<img width="402" alt="Screenshot 2024-06-11 at 11 29 30 PM" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/94101953/60336e82-cea0-4a82-8d91-f3d3abaa5171">
<img width="440" alt="Screenshot 2024-06-11 at 11 29 15 PM" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/94101953/a324b992-5692-4bec-8fb7-8ce843b27773">

It's a little difficult to test further since the UI add product functionality is not currently working. I believe the goal was to be able to add a product and not get default numerical values written to the database for productSize's that don't apply to certain productType's.

Correct me if I'm wrong @keiffer213 but this is for unrelated product fields that aren't displayed in the UI and are still setting default values? For example, you can have productType as Shoes, not enter a productSize but it will still show up as size 'S' in the database.

2024-07-08 23:44 UTC, IsaacJrTypes requested changes
Check the following suggestions, I think it will fix some of the issues you are encountering. One behavior I noticed is @ValidateIf will run first ([decorators are checked sequentially from top to bottom](https://www.typescriptlang.org/docs/handbook/decorators.html#decorator-composition)) and if it fails, the rest of the decorators will not run and validate.

Your code should work as intended once you make the changes, Great Job!

2024-07-08 23:44 UTC, IsaacJrTypes commented on src/products/dto/create-product.dto.ts
> +    @ValidateIf((object, value) => object.productType === 'Shoes')
You can remove `value` for each time not in use in @ValidateIf decorator

2024-07-08 23:44 UTC, IsaacJrTypes commented on src/products/dto/create-product.dto.ts
>      @IsOptional()
Remove @IsOptional decorator

line 15 validates if object.productType matches with 'Shoes'. If it does match, then the next decorator is checked. @IsOptional() will create an entry in the database with an empty array if object.productSizeShoe is empty or is not present in the object payload. Removing @IsOptional decorator will allow @isEnum decorator to run so value of productSizeShoe's value is one of the enum values.

Example
- The image below shows a post request with no productShoeSize in payload. 
![CleanShot 2024-07-08 at 15 50 01](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/36749051/c9b3faea-6551-4f51-a454-bb88cbe89de4)
- Removing @IsOptional decorator will return the error below. Doing so will allow the @isEnum decorator to run and validate the payload.
![CleanShot 2024-07-08 at 15 56 07](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/36749051/509265f3-87b2-4daf-8892-f987bd95b987)

2024-07-30 20:27 UTC, bcko commented
@alasali1 please address the issue requested by Isaac

2025-03-11 18:11 UTC, closed without merging