Add unit tests for archive functionality
SeattleColleges/belindas-closet-nestjs pull request #68
Opened 2023-11-29 08:20 UTC by heosman

Resolves #66 

This PR updates the unit test for the deleet functionality for the product service module (which was no longer working because of changes made to the delete method in products.service.ts) and adds unit tests for archive functionality for the product controller and services modules.

Test results for products.controller.spec.ts:
<img width="563" alt="products controller spec ts results" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/77591083/82d2333a-2972-45d2-8bf9-cf6872882ded">

Test results for products.service.spec.ts:
<img width="550" alt="products service spec ts results" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/77591083/6d1e6d37-8cd8-4313-bb43-91df2301e7a6">

Relates to #45

2023-11-29 19:31 UTC, CourtneyHoppus commented
@heosman it looks like when the delete functionality was changed in pull request #64 that the testing wasn't updated. What you have here doesn't test it fully. But I don't think this is your issue and should probably be addressed in it's own issue. @brinkbrink @taylorpapke @theGaryLarson @tinpham5614 @Robel-003 @Seiyaroo

2023-11-29 19:33 UTC, CourtneyHoppus commented on src/products/services/products/products.service.spec.ts
> +      mockProduct = await service.delete(mockProduct.id);
You want to leave this as before, `const result = await service.delete(mockProduct.id)` as the mockProduct is already defined and we want to see what the service brings back.

2023-11-29 19:44 UTC, CourtneyHoppus requested changes

2023-11-29 19:44 UTC, CourtneyHoppus commented on src/products/services/products/products.service.spec.ts
> +      expect(mockProduct).toEqual(deletedProduct);
Here we still want to compare the `result` to the `deletedProduct`, so it should still be `expect(result).toEqual(deletedProduct);` to use the `result` from the service.

2023-11-29 22:53 UTC, taylorpapke commented
> @heosman it looks like when the delete functionality was changed in pull request #64 that the testing wasn't updated. What you have here doesn't test it fully. But I don't think this is your issue and should probably be addressed in it's own issue. @brinkbrink @taylorpapke @theGaryLarson @tinpham5614 @Robel-003 @Seiyaroo

I would prefer if this was done by @Robel-003 @tinpham5614 or @CourtneyHoppus as they have permission to use our issue naming convention for this and can create the correct issue to target this in a separate PR.

2023-11-30 00:10 UTC, heosman commented
> > @heosman it looks like when the delete functionality was changed in pull request #64 that the testing wasn't updated. What you have here doesn't test it fully. But I don't think this is your issue and should probably be addressed in it's own issue. @brinkbrink @taylorpapke @theGaryLarson @tinpham5614 @Robel-003 @Seiyaroo
> 
> I would prefer if this was done by @Robel-003 @tinpham5614 or @CourtneyHoppus as they have permission to use our issue naming convention for this and can create the correct issue to target this in a separate PR.

My mistake, I'll close this pull request then.

2023-12-02 10:53 UTC, taylorpapke approved these changes
All tests are passing for me just like in your screenshots. @CourtneyHoppus have all the changes that you requested been made?

2023-12-05 21:09 UTC, CourtneyHoppus requested changes
Still reviewing this, but I can see some of the tests aren't quite right and/or complete.
I will continue to work on this.

2023-12-06 03:40 UTC, heosman commented
> @heosman please see the PR #71 I updated the testing for the delete function and all of the work you did on the archive function was based on that. One thing I changed was that when you check for the Bad Request Exception, you use an invalid id and the check in the function catches that automatically. Checking for the Not Found Exception should resolve to a null and we should still check that the model was called, as that is what the function is doing.

@CourtneyHoppus I looked over the changes in your pull request for the delete function test and implemented them in the archive function test. Let me know if it looks alright!

2023-12-07 04:35 UTC, CourtneyHoppus commented
Redirected to #73

2023-12-07 04:35 UTC, closed without merging